Cup 413 get workspace campaigns
AppQuality/unguess_api pull request #8
Opened 2022-04-01 14:54 UTC by cicababba

2022-04-06 18:20 UTC, marcbon requested changes

2022-04-06 18:20 UTC, marcbon commented on src/routes/workspaces/workspaceId/campaigns/_get/index.ts
> +    await getWorkspace(customer_id);
try {
    workspace = await getWorkspace(workspaceId, user.id);
  } catch (error) {
    if ((error as OpenapiError).message == "No workspace found") {
      res.status_code = 404;
      return (error as OpenapiError).message;
    } else {
      res.status_code = 500;
      throw error;
    }
  }

2022-04-06 18:20 UTC, marcbon commented on src/routes/workspaces/workspaceId/campaigns/_get/index.ts
> +
Mancano i controlli anche sugli altri parametri

2022-04-06 18:20 UTC, marcbon commented on src/routes/workspaces/workspaceId/campaigns/_get/index.ts
> +
Se start e limit li ritorni comunque anche quando non ci sono allora mettiamoli required nel response

2022-04-06 18:20 UTC, marcbon commented on src/routes/workspaces/workspaceId/campaigns/_get/index.spec.ts
> +  });
Questi test sui parametri limit e start come fanno a darti PASS? Non ci sono controlli in merito sull'endpoint

2022-04-08 15:44 UTC, cannarocks approved these changes

2022-04-08 15:44 UTC, merged